---
# mostly stolen from kube-prompt
name: release
on:
  create:
    tags:
      - v*
jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.19
        uses: actions/setup-go@v1
        with:
          go-version: 1.19
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
      - name: Build
        env:
          GO111MODULE: on
          GOPATH: /home/runner/work/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export CREATE_EVENT_REF_TYPE=$(jq --raw-output .ref_type "$GITHUB_EVENT_PATH")
          export TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH")
          echo "========================================================="
          echo "DEBUG:" $TAGNAME $CREATE_EVENT_REF_TYPE
          echo "========================================================="
          if [ "$CREATE_EVENT_REF_TYPE" != "tag" ]; then echo "ref_type is not a tag: ${CREATE_EVENT_REF_TYPE}" && exit 78; fi
          ./build.sh cross
          echo "========================================================="
          echo "DEBUG: ls pkg/"
          ls pkg/
          echo "========================================================="
          go install github.com/tcnksm/ghr@latest
          $GOPATH/bin/ghr -n ${TAGNAME} -b "Release ${TAGNAME}" -draft ${TAGNAME} pkg/
